services:
  restful-booker:
    image: ghcr.io/danilfg/restful-booker:latest
    container_name: restful-booker
    ports:
      - "3001:3001"
    networks:
      - elastic

  es01:
    image: ghcr.io/danilfg/elasticsearch:8.8.0
    container_name: es01
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"  # Ограничение памяти
    ports:
      - "9200:9200"
    networks:
      - elastic

  kibana:
    image: ghcr.io/danilfg/kibana:8.8.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200
    ports:
      - "5601:5601"
    depends_on:
      - es01
    networks:
      - elastic
    
  filebeat:
    image: ghcr.io/danilfg/filebeat:8.8.0
    container_name: filebeat
    user: root
    networks:
      - elastic
    depends_on:
      - es01
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
    entrypoint: >
      sh -c 'if [ ! -f /usr/share/filebeat/filebeat.yml ]; then
      echo "
      filebeat.inputs:
        - type: container
          paths:
            - /var/lib/docker/containers/*/*.log
      output.elasticsearch:
        hosts: [\"http://es01:9200\"]
        username: \"elastic\"
        password: \"changeme\"
      " > /usr/share/filebeat/filebeat.yml;
      fi;
      cat /usr/share/filebeat/filebeat.yml;
      filebeat -e'
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200

networks:
  elastic:
    driver: bridge
